### ISSUE TITLE
Missing parameters in the generated OpenAPI specs

### ISSUE THREAD

**Issue by smartie19889** [tailflow/laravel-orion#101]
When generating OpenAPI Specifications, it doesn't create an parameters for use in Swagger. Is this a feature yet? Thanks

**Comment by alexzarbn** [comment]
Hi @smartie19889,

By parameters do you mean query parameters or request body?

**Comment by smartie19889** [comment]
Hi @alexzarbn 

I mean in the request body (i think) so you can easily perform the actions in Swagger without having to know the parameters

Thanks

**Comment by alexzarbn** [comment]
Hi @smartie19889,

Could you please update to [v2.1.0](https://github.com/tailflow/laravel-orion/releases/tag/2.1.0) and see, if you still experience the issue?
