### ISSUE TITLE
(specs) Support for multi-namespace controller allocation

### ISSUE THREAD

**Issue by alexzarbn** [tailflow/laravel-orion#102]
Ref: https://github.com/tailflow/laravel-orion/issues/16#issuecomment-864741126

**Comment by alireza2281** [comment]
@alexzarbn 

The laravel version is on v8.47.0

**Comment by alireza2281** [comment]
@DenisJunio  

I've tested what you suggest to do but did not  fix the problem it still has error on 
`
  $this->router->getRoutes()->getByAction("{$controller}@{$operationName}")
`
when `$operationName`  is search

**Comment by alexzarbn** [comment]
Hi @alireza2281,

Please update to [v2.1.0](https://github.com/tailflow/laravel-orion/releases/tag/2.1.0) - it should be fixed there.
