### ISSUE TITLE
Since v2.0 action Methods `index` are not searching anymore

### ISSUE THREAD

**Issue by josecl** [tailflow/laravel-orion#105]
Starting at v2.0 the method `QueryBuilder->buildQuery()` searches only in `search` actions.
Is this the new behavior or should be available for both: `index` and `search` actions?

In v1.x I was filtering data via query strings on `index` actions.
I want to confirm if I need to update my code accordingly.

Thank you!

**Comment by alexzarbn** [comment]
Hi @josecl,

Yes, it is the new behavior in v2 - search constrains won't be applied for `index` endpoint
