### ISSUE TITLE
Passing an extra attribute on beforeSave

### ISSUE THREAD

**Issue by musixite** [tailflow/laravel-orion#111]
In order to upload a file, I’m sending 2 attributes (imageData and imageLlink)

On beforeSave, i want to upload the imageData but this attribute won’t be saved in the database, only the imageLink

so how do I declare the imageData attribute (and where)?

thanks!

**Comment by alexzarbn** [comment]
Hi @musixite,

This is not related to the package, but rather the business logic of an app itself - please use a specialized forums for questions of this nature - GitHub issues are made specifically for things related to the repository itself, not general questions like this.
