### ISSUE TITLE
Inertia.js support

### ISSUE THREAD

**Issue by jnorms** [tailflow/laravel-orion#116]
Hi, I was thinking here, I know the package has operational focus on creating API's. What do you think the package supports Inertia.js?

**Comment by alexzarbn** [comment]
Hi @jnorms,

Currently there are no plans for implementing something like this for Inertia.js.

**Comment by jjjrmy** [comment]
if there was an option to generate all the controller methods for the routes vs using them from the `Orion::resource()`, then it could be modified to work with Inertia JS.

I think this package would be very useful for Inertia.
