### ISSUE TITLE
Database Transaction

### ISSUE THREAD

**Issue by DavidSprauel** [tailflow/laravel-orion#117]
Hey,

I'm currently working on a project with Orion. I have to performStore an entity but many actions to perform after that.
So i'm using `afterSave` hook. 
My problem is that in my base project I used a try catch to manage error within the script and was using database transaction.

My question is how do you manage to use transaction or use a try catch ? In the `afterSave` ? And I remove my entity if something went wrong in the hook ?

I'd like to add, that if I add a relation in the `afterSave` it won't be sent in the response because the `$entity->fresh()` is done before the `afterSave` where I create my relation.

This is my workflow :

Request sent:
```json
{
    "include": "mainContact",
    "name": "Orion",
    "mainContact": {
        "firstname" : "John",
        "lastname": "Doe",
        "email": "johndoe@gmail.com"
    },
    "location": {
        "address": "3 quai de Paris",
        "city": "Paris",
        "zipcode": 75000,
        "phone": "3333333"
    }
}
```

How I perform operation:
 - performStore
     - generate location
     - create company (with location_id)

- afterSave
    - create the company's mainContact
    - some other actions like notifications etc....
    
The include is not working as the mainContact is created after the `$entity->fresh($requestedRelations)` so it won't be in the response.

**Comment by alexzarbn** [comment]
Transactions support is now available in [v2.2.0](https://github.com/tailflow/laravel-orion/releases/tag/2.2.0) release.

Documentation: https://tailflow.github.io/laravel-orion-docs/v2.x/guide/hooks.html#transactions
