### ISSUE TITLE
This action is unauthorized

### ISSUE THREAD

**Issue by Anfal95** [tailflow/laravel-orion#118]
I have this issue when I remove use DisableAuthorization; line, I have created policy and put it in the AuthServiceProvider

**Comment by alexzarbn** [comment]
Hi @Anfal95,

What auth driver do you use for the api?

**Comment by Anfal95** [comment]
the default one which is api jwt

**Comment by alexzarbn** [comment]
@Anfal95,

Have you configured that correctly? https://laravel.com/docs/5.8/api-authentication#configuration

**Comment by Anfal95** [comment]
yes the configuration is correct

**Comment by Anfal95** [comment]
The issue was solved thank you
