### ISSUE TITLE
Search Pagination issue

### ISSUE THREAD

**Issue by DavidSprauel** [tailflow/laravel-orion#134]
I'm using the endpoint in a relationship `/companies/company_id/documents/search`

As a body of the post:
```json
{
    "search": {
        "value": ""
    },
    "page": 1,
    "limit": 5,
    "sort": [
        {
            "field": "created_at",
            "direction": "desc"
        }
    ]
}
```

When I requiert page 1 no problem, let's say I got 88, 87, 86 , 85, 78 as ids and when i requiert page 2 i got 78, 79, 80, 81, 82 which generate error in my front-end.
I tried to remove my custom `buildIndexFetchQuery` but same.

Then I tried to remove the sort and it works. it seems like the sorting cause problems and I didn't found yet why.
Any ideas ? 

Of course in my controller, I have
```php
public function searchableBy(): array
    {
        return ['name', 'filename'];
    }

    public function sortableBy(): array
    {
        return ['created_at'];
    }
``` 

EDIT: after checking in the database from 78 to 84 they have the same date. guess it is for that reason.

**Comment by nvtdien** [comment]
how to search + pagination combine
