### ISSUE TITLE
Get page from meta data

### ISSUE THREAD

**Issue by keksum666** [tailflow/laravel-orion#138]
Hello everyone, can I pull meta data from query builder?

To get the data, I use the following code:
![image](https://user-images.githubusercontent.com/47279073/145800033-47e07c0d-e0b7-4fa8-8cfd-29433ab07797.png)

Response:
![image](https://user-images.githubusercontent.com/47279073/145800204-e0434f66-114b-428c-8b90-230bf0c50a00.png)

The problem is that it returns an array of objects at once, is there any way around this?

**Comment by alexzarbn** [comment]
Hi @keksum666,

Each model returned by the API is populated with `$request` property that contains a complete response, including the `meta` field. Please also refer to [this](https://github.com/tailflow/laravel-orion-ts/issues/5) issue.

P.S. The question is not related to that repository - should be created in [TypeScript SDK](https://github.com/tailflow/laravel-orion-ts) repository.
