### ISSUE TITLE
is there any roadmap for Swagger UI?

### ISSUE THREAD

**Issue by FareedR** [tailflow/laravel-orion#145]
similar like this?

https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger/_static/swagger-ui.png?view=aspnetcore-6.0

**Comment by alexzarbn** [comment]
Hi @FareedR,

No, it is outside of scope of this project. Orion can generate OpenAPI specs, but how to use these specs to render the documentation is up to you.

There are projects like [Redoc](https://github.com/Redocly/redoc) that do what you might be looking for.
