### ISSUE TITLE
Filtering json data

### ISSUE THREAD

**Issue by axtg** [tailflow/laravel-orion#155]
I'm running into the challenge that I'm getting unexpected results when I apply a filter to an endpoint as below. 
Seems like a filter on 500 is read as 5. 

My data (tracks.configuration) contains maxProducts between 0 and 5.

Observations:
_I'm not running this in a single request, but for readability added to one view_
_Same holds when values are unquoted (e.g. not "400" but 400)_
```
{
	"filters" : 
	[
		{
			"field" : "tracks.configuration->maxProducts", "operator" : ">", "value": "4" // Returns results as expected
			"field" : "tracks.configuration->maxProducts", "operator" : ">", "value": "6" // Returns no results as expected
		  --> "field" : "tracks.configuration->maxProducts", "operator" : ">", "value": "400" // Returns results unexpectedly
			"field" : "tracks.configuration->maxProducts", "operator" : ">", "value": "600" // Returns no results as expected
		}
	]
}

**Comment by alexzarbn** [comment]
Hi @axtg,

Could you please provide a sample of how data is stored in db for the `maxProducts` column?

**Comment by alexzarbn** [comment]
@axtg,

Are you 100% sure `maxProducts` is always a number, not a string, e.g. `"5"`?

**Comment by axtg** [comment]
Fair question, wouldn't be the first time.
Just checked. It only concerns 91 rows. All 91 of them are integers. 

The only transposing is through the $casts attribute.

```
    protected $casts = [
        'configuration' => 'array',
    ];
```

**Comment by alexzarbn** [comment]
@axtg,

Hmm, interesting case, I will try to replicate the issue locally on the weekend.

**Comment by alexzarbn** [comment]
@axtg 

Turned out to be a PostgreSQL thing. Because it sees that your data is numeric, but you pass "400", which is a string, it casts it automatically to a number.

Do not use string values when comparing numbers, and everything should work as intended.
