### ISSUE TITLE
Security: Includes

### ISSUE THREAD

**Issue by horstoeko** [tailflow/laravel-orion#156]
Hi!

Imagine the following situation: I have a blog post. A blog post has meta-data as a 1:n relation. Now I have a controller for the blog posts and a RelationController for the metadata of the blog post. Both the blog posts and the metadata of a blog post are secured by policies. This works absolutely correctly and flawlessly. 

But when I allow my controller (the one for the blog posts) to include the metadata with the include query parameter (URL), the policy for the associated metadata is not taken into account.

I think this is a serious problem - or am I making a mistake?

**Comment by alexzarbn** [comment]
Hi @horstoeko,

Partially - yes, it might be (or should I say, should be) a security concern, but it is up to a developer to ensure that included relation entities are retrieved and scoped accordingly, when used in model-level controller. This can be accomplished via [query customization](https://tailflow.github.io/laravel-orion-docs/v2.x/guide/models.html#customizing-queries).
