### ISSUE TITLE
[Question] Different Resource Response depending on endpoints.

### ISSUE THREAD

**Issue by francoisauclair911** [tailflow/laravel-orion#160]
Hi

Is it possible to use different Collection/Resource for different endpoint on the same controller?
I would like the `index` method to return a shorter list of attributes than the `show` method for example.

Thank  you

**Comment by SachinGanesh** [comment]
Hi, 

You can override the resource like this

```php

protected function afterIndex(Request $request, $project)
{
        $this->resource = MinimalResource::class;
}

protected function afterShow(Request $request, $project)
{
        $this->resource = FullResource::class;
}

```
