### ISSUE TITLE
Create or update

### ISSUE THREAD

**Issue by axtg** [tailflow/laravel-orion#161]
I need some help.

I'm posting a payload (`session_id`, `state_id`, `values`) to my endpoint with the intention to create a new row.
However, if the combination of `session_id` and `state_id` already exists, I'd like to update the `values` column for the existing row instead of creating a duplicate entry.

If I wrap this within the performStore() I'm getting a "wasRecentlyCreated" on null. Fair, because that doesn't exist if I updated.
But then... How do I determine whether to update or create a row given the payload?

**Comment by axtg** [comment]
For now I'll just stick with overwriting the `store()` method. Here I use the Laravel native `updateOrCreate()` method, yet I feel I might miss out on some Orion magic then.

**Comment by alexzarbn** [comment]
Hi @axtg,

Upsert operation is currently not available, but is planned for the coming releases.

For now, I would suggest looking into the `performStore` and `store` methods and how you could orchestrate it to fit your app needs.
