### ISSUE TITLE
[Feature Request] Ability to set the number of records per page

### ISSUE THREAD

**Issue by pakomp** [tailflow/laravel-orion#164]
Would be great to be able to set the number of records returned per page.

**Comment by alexzarbn** [comment]
Hi @pakomp

It is already possible by either providing `limit` query parameter of overriding `limit()` method on a controller.

Missing in the docs though - will update it, thanks for pointing out the problem.

**Comment by alexzarbn** [comment]
Docs: https://tailflow.github.io/laravel-orion-docs/v2.x/guide/query-parameters.html#pagination-limit

**Comment by pakomp** [comment]
Thank you for updating the docs! @alexzarbn :+1:
