### ISSUE TITLE
How to define a catch-all route

### ISSUE THREAD

**Issue by hardikdangar** [tailflow/laravel-orion#176]
I have pages as my model. and i am binding it via,

`Orion::resource('pages', PageController::class)->where(['page', '([0-9A-Za-z/\s-]*)'])->only(['index', 'show']);`

above does work for single routes like 
/api/pages/about

but it doesn't work for nested routes.
/api/pages/about/faq

I know laravel has any route so i can do it that way but orion doesn't have that. i even tried,
`Orion::resource('pages/about', PageController::class)->only(['show']);`
but this tries to find faq model so not sure how i can achieve that with orion. tried going through docs but nothing on documentation as well.

**Comment by hardikdangar** [comment]
@GautierDele can you help me with this

**Comment by alexzarbn** [comment]
Hi @hardikdangar,

Might be a typo in your regex - escape the `\` character: `([0-9A-Za-z\/\s-]*)`

https://regex101.com/r/lxLz6P/1

![Screen Shot 2022-09-09 at 10 39 56](https://user-images.githubusercontent.com/12220926/189279102-25c448ef-313c-4dcb-8555-f00136c77b8a.png)

![Screen Shot 2022-09-09 at 10 39 13](https://user-images.githubusercontent.com/12220926/189279055-448f1797-0861-403e-a87e-dcc3980fbfe7.png)
