### ISSUE TITLE
Custom controller function

### ISSUE THREAD

**Issue by jeroenqui** [tailflow/laravel-orion#182]
I have the following situation: I want to get filtered (open) and grouped (by status) tickets

I have come up with the following solution:

### Added in routes/api.php
`Route::post('tickets/grouped/{groupBy}', 'TicketController@getGrouped');`

### Frontend POST request to tickets/grouped/ticket_status_id with this param
`filters: [{ "field": "closed", "operator": "=", "value": "0" }]`

### TicketController.php
```
public function getGrouped(Request $request)
{
    return $this->search($request)->groupBy($request->groupBy);
}
```

The problem is that the grouping is applied, but the filters are not.
Even when I just do this, it's not applied:

### TicketController.php
```
public function getGrouped(Request $request)
{
    return $this->search($request);
}
```

Also tried:
`return $this->search($request);`

When I make the same POST request, but to the /tickets/search endpoint it does work fine.
What am I missing here? Or should I try a different approach to achieve this?

**Comment by GautierDele** [comment]
We can't debug you application with just those details. Be aware you are using a deprecated (if not abandonned) way of declaring routes https://laravel.com/docs/9.x/routing#the-default-route-files

**Comment by jeroenqui** [comment]
@GautierDele thanks for your answer and time reading this.
I'm aware of the deprecated way of declaring routes, but thanks for pointing that out.

Perhaps you could help by globally telling how you would achieve this result (filter and then group) without using hooks (as it would affects all calls to that endpoint)?

**Comment by GautierDele** [comment]
You can't call the search function because this returns a collection response.

In my opinion the best way to achieve this would be to override the "buildFetchQuery" hook and conditionnally add your groupBy

```php
    protected function buildFetchQuery(\Orion\Http\Requests\Request $request, array $requestedRelations): Builder
    {
        parent::buildFetchQuery($request, $requestedRelations);
        
        if ...
    }
```

**Comment by jeroenqui** [comment]
@GautierDele Great, thank you! I wouldn't have thought of that approach!
