### ISSUE TITLE
Specify pagination size on backend

### ISSUE THREAD

**Issue by GautierDele** [tailflow/laravel-orion#185]
Hello there,

I was wondering why the "size" query parameter was so uncontrolled. In my opinion it's quite dangerous to allow front end users to determine their size since they can crash your API.

I would have think of a new controller function like:

```php
function paginationSizes() {
  return [25, 50, 100];
}
```

It would be great to be able to provide params such as "< 1000" to just limit the size to a ceil.

What do you think ?

**Comment by alexzarbn** [comment]
Hi @GautierDele,

Yes, it would make sense to limit the maximum number of entities. Something like this:

```
protected $paginationLimit = 500;
```

Having strictly defined pagination sizes is too limiting though.
