### ISSUE TITLE
Includes are broken in version 2.17.0

### ISSUE THREAD

**Issue by teyeheimans** [tailflow/laravel-orion#188]
Since version 2.17.0 our "include" with a relation is broken. In version 2.16.0 this still works.

My test case:
```
$this->post('api/attachments/search?include=chatMessage,chatMessage.to,chatMessage.from')->assertOk();
```

This used to work, but now it gives an 500 status. It now throws an exception, while this works in the previous version. The exception:

```
{#4430
  +"message": "Call to undefined method App\Models\Media::chatMessage.to()"
  +"exception": "BadMethodCallException"
  +"file": "<path>/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php"
... etc.
```

My Controller looks like this:

```
class AttachmentsController extends Controller
{
    protected $model = Media::class;

    public function includes(): array
    {
        return ['chatMessage', 'chatMessage.*'];
    }
    
    // ... etc
}
```

**Comment by axtg** [comment]
I can confirm seeing the same.
Type of relation in my case is of "BelongsToThrough" of [this package](https://github.com/staudenmeir/belongs-to-through). @teyeheimans Does that hold for you too, or is it a wider relationship problem?

**Comment by jasper-ter-veen** [comment]
The following code in `src/Drivers/Standard/QueryBuilder`
```
    /**
     * Get the model class from a given relation.
     *
     * @param string $relation
     * @return string
     */
    public function getRelationModelClass(string $relation): string
    {
        return get_class((new $this->resourceModelClass)->$relation()->getModel());
    }
```

can't handle nested relations like `chatMessage.to`

**Comment by horstoeko** [comment]
I can confirm seeing the same.

**Comment by alexzarbn** [comment]
Published a fix in v2.17.1. Could you please let me know, if the problem is resolved for all of your apps?

**Comment by axtg** [comment]
Confirmed working for the 2 request(s) I ran into a 500 before yes.

**Comment by horstoeko** [comment]
@alexzarbn I can confirm, that the problem is gone for me too.

**Comment by teyeheimans** [comment]
Wow, that was quick! Indeed, version v2.17.1 solves this issue!

**Comment by jeroenqui** [comment]
Sorry, for me it's still not working on the 'search' endpoint. 

It does work fine on this request (for example): GET 'api/attachments/1?include=chatMessage,chatMessage.to,chatMessage.from'

But it doesn't work like this (for example): POST 'api/attachments/search?include=chatMessage,chatMessage.to,chatMessage.from'

It's not throwing an error, but it doesn't include the relation.

On this docs page: https://tailflow.github.io/laravel-orion-docs/v2.x/guide/search.html#includes
I see you need to use a different approach to include relations. 
That would mean a breaking change was introduced?

**Comment by alexzarbn** [comment]
@jeroenqui No, the intention was to be able to use both query and post params in the `search` endpoint to include relations. The "post" version just allows for filters to be applied on the includes. If the "query" version is not working on the search endpoint, then it is a potential bug.

Could you please check, if the relation is not included, even if the "post" version of includes is used?

**Comment by jeroenqui** [comment]
@alexzarbn 
When I use the "post" version of includes:

Endpoint: /api/tickets/search

``includes: [
    { relation: 'customer' },
    { relation: 'user' }
]``

Error 500
`Call to undefined method App\\Models\\Customer::user()`


Even when I try this in my controller:

``public function alwaysIncludes(): array
    {
        return [
            'customer',
            'user'
        ];
    }``

relations are not included.

**Comment by shafiramaki** [comment]
> @alexzarbn When I use the "post" version of includes:
> 
> Endpoint: /api/tickets/search
> 
> ```
> includes: [
>     { relation: 'customer' },
>     { relation: 'user' }
> ]
> ```
> 
> Error 500 `Call to undefined method App\\Models\\Customer::user()`
> 
> Even when I try this in my controller:
> 
> ```
> public function alwaysIncludes(): array
>     {
>         return [
>             'customer',
>             'user'
>         ];
>     }
> ```
> 
> relations are not included.



> @alexzarbn When I use the "post" version of includes:
> 
> Endpoint: /api/tickets/search
> 
> ```
> includes: [
>     { relation: 'customer' },
>     { relation: 'user' }
> ]
> ```
> 
> Error 500 `Call to undefined method App\\Models\\Customer::user()`
> 
> Even when I try this in my controller:
> 
> ```
> public function alwaysIncludes(): array
>     {
>         return [
>             'customer',
>             'user'
>         ];
>     }
> ```
> 
> relations are not included.

have same issue!

**Comment by alexzarbn** [comment]
Hi @jeroenqui,

Could you please share the following:

1. The `$model` property value of the affected controller and the contents of that model class
2. The `alwaysIncludes` method contents as it was specified before/during update to v2.17.0
3. The `includes` method contents as it was specified before/during update to v2.17.0

**Comment by jeroenqui** [comment]
1. protected $model = 'App\Models\Ticket';


2. I just used it for test:
'''
    public function alwaysIncludes(): array 
     { 
         return [ 
             'customer',
             'ticketAccessoire', 
             'ticketStatus', 
             'ticketCategory', 
             'ticketPaymentMethod', 
             'ticketUpdate', 
             'user' 
         ]; 
     }
'''

3.
'''
    public function includes(): array 
     { 
         return [ 
             'customer', 
             'customer.*', 
             'ticketAccessoire', 
             'ticketStatus', 
             'ticketCategory', 
             'ticketPaymentMethod', 
             'ticketUpdate', 
             'user' 
         ]; 
     }
'''

**Comment by alexzarbn** [comment]
@jeroenqui,

Okay, thanks, could you please also share the contents of the `Ticket` model class?

**Comment by jeroenqui** [comment]
```
<?php 
  
 namespace App\Models; 
  
 use Illuminate\Database\Eloquent\Factories\HasFactory; 
 use Illuminate\Database\Eloquent\Model; 
 use Illuminate\Database\Eloquent\SoftDeletes; 
  
 class Ticket extends Model 
 { 
     use HasFactory, SoftDeletes; 
  
     protected $fillable = [ 
         'ticket_number', 
         'customer_id', 
         'user_id', 
         'ticket_category_id', 
         'ticket_status_id', 
    .... Etcetera
     ]; 
  
     public function customer() 
     { 
         return $this->belongsTo(Customer::class); 
     } 
  
     public function ticketAccessoire() 
     { 
         return $this->belongsTo(TicketAccessoire::class); 
     } 
  
     public function ticketCategory() 
     { 
         return $this->belongsTo(TicketCategory::class); 
     } 
  
     public function ticketStatus() 
     { 
         return $this->belongsTo(TicketStatus::class); 
     } 
  
     public function ticketPaymentMethod() 
     { 
         return $this->belongsTo(TicketPaymentMethod::class); 
     } 
  
     public function ticketHardwareBrand() 
     { 
         return $this->belongsTo(TicketHardwareBrand::class); 
     } 
  
     public function ticketHardwareStorage() 
     { 
         return $this->belongsTo(TicketHardwareStorage::class); 
     } 
  
     public function ticketProduct() 
     { 
         return $this->hasMany(TicketProduct::class); 
     } 
  
     public function ticketUpdate() 
     { 
         return $this->hasMany(TicketUpdate::class); 
     } 
  
     public function user() 
     { 
         return $this->belongsTo(User::class); 
     } 
 }
```

**Comment by alexzarbn** [comment]
@jeroenqui

Please update to the v2.17.3 and see if it fixes the issue.

**Comment by jeroenqui** [comment]
@alexzarbn v2.17.3 fixes the inclusion of the includes specified on alwaysIncludes, but it still doesn't work with either GET/include or POST/includes (without specifying alwaysIncludes)

**Comment by alexzarbn** [comment]
@jeroenqui Hmm, that's really strange, includes are working just fine in tests and on my local setup 🤔

Few more questions:
- What Laravel version do you use?
- Do you override any hook/build methods on a controller?
- When making a request, what values do you use (if any) in `Accept` and `Content-Type` headers?

**Comment by jeroenqui** [comment]
@alexzarbn This last test I tested on a different frontend view.
This view was using the POST version of include (without s) with a string value. 
This was working fine pre 2.16, but doesn't work on 2.17.3

So, to summarize:
With 2.17.3 the GET version of include does work fine!
With 2.17.3 the POST version of includes with an array->object value works fine!
With 2.17.3 the POST version of include with a string value doesn't work.

But if I check the docs now, the POST version with include with a string value, isn't even supposed to be working, as it's mentioned nowhere.

So, for me this is a breaking change, but it's not a bug in the current version.
It's probably just a bug in the pre 2.16 versions that this was working for me.
I was just using this bug as a feature, it seems :-)

**Comment by alexzarbn** [comment]
@jeroenqui Ah, okay, in that case it is indeed an incorrect usage of the feature, not a bug. if you supply `include` parameter in the post body instead of `includes` - it won't work, as it expects either a query parameter `include` (that is a string with a comma separated relations) or a post body parameter `includes` (that is an array of objects).

**Comment by teyeheimans** [comment]
I still have issues regarding this case. 

For example, I have this test:
```
$response = $this->post(
            '/api/availabilities/search',
            [
                'include' => 'user',
                'scopes'  => [
                    [
                        'name'       => 'day',
                        'parameters' => [now()->format('Y-m-d')],
                    ],
                ],
            ],
            ['Accept' => 'application/json']
        );
```        

The response in version 2.16.0. is (filled with faker data):

```
array:1 [
  "data" => array:1 [
    0 => array:13 [
      "id" => 1
      "created_at" => "1970-09-07T23:35:07.000000Z"
      "updated_at" => "2009-11-15T10:53:13.000000Z"
      "user_id" => 1
      "state" => "out-of-office"
      "start_date" => "2022-11-04T00:00:00.000000Z"
      "start_day_part" => "all-day"
      "end_date" => "2022-11-04T00:00:00.000000Z"
      "end_day_part" => "all-day"
      "repeat" => null
      "repeat_until" => null
      "extra_information" => null
      "user" => array:10 [
        "id" => 1
        "created_at" => "1986-10-13T12:24:34.000000Z"
        "updated_at" => "1987-06-10T19:02:09.000000Z"
        "first_name" => "Kaley Schuster"
        "email" => "jose.kulas@example.net"
        "birthday" => "1995-06-29T10:45:07.000000Z"
        "department" => "Techniek"
        "is_admin" => false
        "last_name" => "Prof. Ethyl Feil II"
        "availabilities" => []
      ]
    ]
  ]
]
```

In version 2.17.3, the response now is:
```
array:1 [
  "data" => array:1 [
    0 => array:12 [
      "id" => 1
      "created_at" => "2010-02-08T22:44:23.000000Z"
      "updated_at" => "1982-01-03T22:15:38.000000Z"
      "user_id" => 1
      "state" => "unavailable"
      "start_date" => "2022-11-04T00:00:00.000000Z"
      "start_day_part" => "all-day"
      "end_date" => "2022-11-04T00:00:00.000000Z"
      "end_day_part" => "morning"
      "repeat" => "every-2-weeks"
      "repeat_until" => "2023-05-21T00:00:00.000000Z"
      "extra_information" => null
    ]
  ]
]
```

As you can see, the user is missing.

**Comment by teyeheimans** [comment]
I see that in the file `src/Drivers/Standard/RelationsResolver.php` the `requestedRelations` method does not include the relation if it is posted.

Changing line 44:
```
$requestedIncludesQuery = collect(explode(',', $request->query('include', '')));
```

To:
```
$requestedIncludesQuery = collect(explode(',', $request->get('include', '')));
```
Seems to resolve this issue.

**Comment by DavidSprauel** [comment]
Could this solution be updated in the package ? I had to change a file of the package myself for it to work :/
