### ISSUE TITLE
Specify required query parameters for resources

### ISSUE THREAD

**Issue by JonErickson** [tailflow/laravel-orion#207]
Hello, is there any way to specify additional query parameters for a resource that is required? For example, I had a multi-tenant application that requires either a header set or query parameter set which each request for our API and want to include that in the auto-generated spec. Thanks.

**Comment by alexzarbn** [comment]
Hello,

Currently it's not possible, but you can always add the query parameters to the specs manually - they won't be overwritten upon spec generation.

Also this thread might be worth following: https://github.com/tailflow/laravel-orion/issues/180
