### ISSUE TITLE
Impossible sort with MorphToMany relation

### ISSUE THREAD

**Issue by Samoht70** [tailflow/laravel-orion#208]
Hello,

I have a problem when I want to do a sort with laravel orion on a MorphToMany relation. I get this error: 

> "message": "Call to undefined method Illuminate\\Database\\Eloquent\\Relations\\MorphToMany::getQualifiedForeignKeyName()".

After trying to see where the error came from, I came to this `relationForeignKeyFromRelationInstance()` function in the `RelationsResolver.php` and indeed, I have the impression that it is not possible to do a sort on a MorphToMany and I think it is the same for the BelongsToMany.

Can this be confirmed?

Thanks for your help

**Comment by alexzarbn** [comment]
Hello @Samoht70,

What Laravel version do you use?

**Comment by Samoht70** [comment]
I am using laravel version 9.2

**Comment by GautierDele** [comment]
Can confirm this, I also have a problem when including relation of a polymorphic relation, no results are given

**Comment by alexzarbn** [comment]
Hmm, I can't replicate it 🤔

@Samoht70 Was it working before or it stopped working after some upgrade?
@GautierDele What is your Laravel version? As for the relation inclusion, please open a separate issue.

**Comment by GautierDele** [comment]
I am on the 9 also, I just upgraded laravel orion and it seems like not working the same, i'll investigate further to establish a diagnostic

**Comment by alexzarbn** [comment]
Actually, no, it's not possible to sort in such a way, because there are multiple rows for sort to rely on. If, for instance, two posts have multiple tags, and you are trying to sort posts by tags name, what tag name should be used for comparison?

However, sorting by pivot field is possible, because there is only one pivot row for each associated entry.
