### ISSUE TITLE
Convention for JSON response

### ISSUE THREAD

**Issue by axtg** [tailflow/laravel-orion#21]
First off: so happy with this package. Exactly what the doctor ordered. 

The one thing I'm uncertain of (happy to hear your thoughts) is the default JSON response. I'm used to it container a status, message, and data object. And for errors showing status, message and errors object (through a custom exception). So far, though that might be because I drew it into an existing project, I'm getting non-JSON exceptions. And successful calls do not contain status or message (e.g. 200, resource update, data{}).

So I'd be curious to learn what conventions are followed in this project.

Keep it up!

**Comment by PascalHesselink** [comment]
This package is lightweight due the working of default Laravel behaviour, personally I don't think that should be changed.

**Comment by axtg** [comment]
I guess you're right. I am taking this too far.
And I can still keep my custom exceptions, catching the NotFoundHttpException, etc.
