### ISSUE TITLE
[Question] How to add additional information to generated documentation?

### ISSUE THREAD

**Issue by renepardon** [tailflow/laravel-orion#210]
I would like to add additional information (description or example values) to example/schema parameters. Is there a way to do so?

**Comment by alexzarbn** [comment]
Hello @renepardon,

Currently no, but you can add additional information directly to the generated specs - it won't be overwritten.

**Comment by renepardon** [comment]
Hi @alexzarbn 
Do you think a feature with reflection would help to „overrule“ some things? For example for adding descriptions or overriding types of properties?
Also the the resources are not respected. All „fillable“ attributes are used for response examples and not the fields defined in the response transformers.
