### ISSUE TITLE
Selecting fields

### ISSUE THREAD

**Issue by emeGuan** [tailflow/laravel-orion#211]
Is it possible to select the fields to return via url? And in relationships?
Something like this:
https://spatie.be/docs/laravel-query-builder/v5/features/selecting-fields
Or to this:
https://laraveljsonapi.io/docs/2.0/schemas/attributes.html#sparse-fields
Regards.

**Comment by alexzarbn** [comment]
Hello,

No, currently it is not possible. Leaving the issue open to see, if there is a demand for this.

**Comment by alexzarbn** [comment]
Duplicate of https://github.com/tailflow/laravel-orion/issues/128
