### ISSUE TITLE
Filtering relationships with LIMIT

### ISSUE THREAD

**Issue by niels-hubs** [tailflow/laravel-orion#217]
Hi,

Curious, I have a chat model with messages. And for the chat overview screen I only want to have the latest message and to limit the amount of responses from that relation.

So I use the search operation, with a include, and a filter but I don't see a way to limit the amount of responses I get from that relation inside the search filters.

Is there a way to easily achieve this? In plain eloquent I can easily do this $query->latest()->take(5).

Kind regards,
Niels

**Comment by alexzarbn** [comment]
Hi @niels-hubs,

Starting from [v2.20.0](https://github.com/tailflow/laravel-orion/releases/tag/2.20.0) it is possible to provide `limit` field in a include relation descriptor to limit he number of included relation entities.
