### ISSUE TITLE
Can't sort based on created_at in HasMany relationship

### ISSUE THREAD

**Issue by niels-hubs** [tailflow/laravel-orion#219]
Hi,

Thanks for this great library! It really helps saving some time.
I do however have a question related to the sorting of the created_at when using a HasMany relationship. I am using the search method. I am using Laravel 10.

```     
 "message": "Call to undefined method Illuminate\\Database\\Eloquent\\Relations\\HasMany::getQualifiedLocalKeyName()",
``` 

I get the above error message when using a HasMany relationship.

I've added

``` 
   public function sortableBy() : array
    {
         return ['messages.created_at'];
    }
```

```    
   public function messages(): HasMany {
        return $this->hasMany(ChatMessage::class);
    }
```

```
    "sort" : [
        {"field" : "messages.from_user_id", "direction" : "asc"}
    ]
```

Am I doing something wrong, or is this a bug and is there a workaround? 

Thank you!

**Comment by alexzarbn** [comment]
Hello @niels-hubs,

It is not possible to sort parent resources this way, because, if (whatever the parent resource for messages is) has multiple messages, which message should it use for sorting?
