### ISSUE TITLE
Using slug instead of model ID

### ISSUE THREAD

**Issue by densityx** [tailflow/laravel-orion#22]
is it possible to make use of slug istead of id?

```php
/**
* Get the route key for the model.
*
* @return string
*/
 public function getRouteKeyName()
{
    return 'slug';
}
```

so far using slug gave me `SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bigint:` error

**Comment by alexzarbn** [comment]
Yes, it is possible, for now the only way is to customize the Eloquent query used to fetch models.
Please take a look at the [documentation](https://tailflow.github.io/laravel-orion-docs/guide/models.html#customizing-queries).

I will look into providing the support for using the value from `getRouteKeyName()` 👌

**Comment by alexzarbn** [comment]
The ability to customize resource keys on both [model](https://tailflow.github.io/laravel-orion-docs/guide/models.html#customizing-keys) and [relation](https://tailflow.github.io/laravel-orion-docs/guide/relationships.html#customizing-keys) resources is added in 1.2 release.
