### ISSUE TITLE
filterableBy nested relation: Call to undefined method

### ISSUE THREAD

**Issue by thiagok2** [tailflow/laravel-orion#229]
Hey
Firstly, congratulations on the fantastic framework! I am new to Orion and currently using version 2.21.
I'm using the search feature and I want to apply a nested filter on an entity of a second-level relationship. I have already configured the config/orion.php file with the property 'max_nested_depth' => 5 and published it. 

My Model A has a BelongsTo relationship with Model B, which in turn has a BelongsTo relationship with Model C. In Model B, I have added with('b') to the mapping. In the controller, I have used filterableBy with one of the values from the array: 'b',b.c' and 'b.c.property', and in the query body, I have the following JSON:

`
{
    "filters": [
        { "field": "b.c.property", "operator": "ilike", "value": "A%" }
    ]
}
`

I have also added the relationships 'b' and 'b.c' in the include and alwaysIncludes methods. However, despite trying various configuration combinations, I always receive the following error message:

`
{
    "message": "Call to undefined method App\\Models\\A::b.c()"
}
`

It seems like you are trying to access a nested relationship in your search filter but encountering an error. Please make sure that your relationship mappings in the Laravel models are correctly defined. Instead of accessing the nested relationship as 'b.c', you should use dot notation and access it as 'b.c.property'. Here's an updated version of the query body:

`
{
    "filters": [
        { "field": "b.c.property", "operator": "ilike", "value": "A%" }
    ]
}
`
I'm not sure what else to do, as I haven't attempted to change the version since it's already on a recent version. Where am I going wrong?

**Comment by alexzarbn** [comment]
Hi @thiagok2,

Filtering by more than 1 level of relationship is not supported. 
Perhaps you misunderstood the meaning of "nested" filters. Please check the corresponding [documentation](https://tailflow.github.io/laravel-orion-docs/v2.x/guide/search.html#nested-filters).
