### ISSUE TITLE
How can i set default get record order by id descending order?

### ISSUE THREAD

**Issue by nishantp306** [tailflow/laravel-orion#232]
right now we are getting default record by order id asc. i want to set id desc. can any one guide me how can i set it?

**Comment by alexzarbn** [comment]
Hi @nishantp306,

You can [customize](https://tailflow.github.io/laravel-orion-docs/v2.x/guide/models.html#customizing-queries) the default sorting of query using `buildIndexFetchQuery` method on a controller.
