### ISSUE TITLE
API response always returns "403 This action is unauthorized"

### ISSUE THREAD

**Issue by AEK-BKF** [tailflow/laravel-orion#24]
Hello,
First of all, thank you so much for this amazing package,
I have same issue as this one : [https://github.com/tailflow/laravel-orion/issues/20](https://github.com/tailflow/laravel-orion/issues/20)

I cannot figure out the mistake ! I defined every thing, and it works fine if I put : `DisableAuthorization`.
 

Thanks

**Comment by rodrigotbrun** [comment]
Did you set your Policies in AuthServiceProvider ?

I was trying this package for the first time, and its amazing, btw.. And I was getting 403, only because I did not set already in the AuthServiceProvider.

**Comment by AEK-BKF** [comment]
@rodrigotbrun thanks for reply,,
 Yes I set it as well,

**Comment by rodrigotbrun** [comment]
And what about your Request class, `authorize` method is returning true?

**Comment by AEK-BKF** [comment]
Okey, here's the code : 
Note That I'm using : Latest Laravel 8, Sanctum, NuxtJs.
Exam Page requires Auth middleware 

- Api Route : 
```
Route::middleware('auth:sanctum')->group(function() {
    Orion::resource('exams', ExamController::class);
```
- Controller : 
```
<?php

namespace App\Http\Controllers\Api;

use Orion\Http\Controllers\Controller;
//use Orion\Concerns\DisableAuthorization;
use Illuminate\Http\Request;
use App\Models\Exam;

class ExamController extends Controller
{
    //use DisableAuthorization;
    protected $model = Exam::class;
    protected $relation = 'user';
}

```

- Model : 
`App\Models\Exam`
- Model Policy :  
App\Policies\ExamPolicy
```
<?php

namespace App\Policies;

use App\Models\Exam;
use App\Models\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class ExamPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view any models.
     *
     * @param  \App\Models\User  $user
     * @return mixed
     */
    public function viewAny(User $user)
    {
        return true;
    }

    /**
     * Determine whether the user can view the model.
     *
     * @param  \App\Models\User  $user
     * @param  \App\Models\Exam  $exam
     * @return mixed
     */
    public function view(User $user, Exam $exam)
    {
        //return true;
        return $user->id == $exam->user_id;
                /* ? Response::allow()
                : Response::deny('You do not own this post.'); */
    }
```
- AuthServiceProvider : 
```
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        //Exam::class => ExamPolicy::class,
        'App\Models\Exam' => 'App\Policies\ExamPolicy',
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        //
    }
}

```

Thanks

**Comment by alexzarbn** [comment]
Hi @AEK-BKF,

You need to override the `resolveUser` method on a controller that is using Auth guard other than `api`.
Please take a look at the [docs](https://tailflow.github.io/laravel-orion-docs/guide/security.html#authorization).

**Comment by rodrigotbrun** [comment]
> Hi @AEK-BKF,
> 
> 
> 
> You need to override the `resolveUser` method on a controller that is using Auth guard other than `api`.
> 
> Please take a look at the [docs](https://tailflow.github.io/laravel-orion-docs/guide/security.html#authorization).

That's a good point.
I was reviewing my code, and your code. I'm using a custom guard as well, and I've implemented this ResolveUser method, along with correct policy model injection. 

This should work!

**Comment by AEK-BKF** [comment]
@alexzarbn Thank you so much!
I fixed it by setting : 
```
public function resolveUser()
    {
        return auth()->user();
    }
```
But, should I put this in every controller ?

**Comment by rodrigotbrun** [comment]
> @alexzarbn Thank you so much!
> 
> I fixed it by setting : 
> 
> ```
> 
> public function resolveUser()
> 
>     {
> 
>         return auth()->user();
> 
>     }
> 
> ```
> 
> But, should I put this in every controller ? 

I've created a controller that does this. And I extend in my api controllers. To avoid always overriding this. 

I suggest adding some trait.

**Comment by AEK-BKF** [comment]
Thank you so much :+1:

**Comment by Anfal95** [comment]
I have the same issue, the code works fine if I put use DisableAuthorization
I have created policy, and put it in the AuthServiceProvider

**Comment by jamorera** [comment]
> @alexzarbn ¡ Muchas gracias!
> Lo arreglé configurando:
> 
> ```
> public function resolveUser()
>     {
>         return auth()->user();
>     }
> ```
> 
> Pero, ¿debería poner esto en cada controlador?

**Comment by rcianor** [comment]
Exists one codition: if the migration aren´t the timestamps atributes and the Laravel try to write this. Verify if in the Model have this:   public $timestamps = false;

Hugs.
