### ISSUE TITLE
Can't use 'max_nested_depth' => 1 with in Request

### ISSUE THREAD

**Issue by RulianZB** [tailflow/laravel-orion#240]
Hi, i got a problem when i call a request Orion

![Capture d'écran 2023-11-15 101253](https://github.com/tailflow/laravel-orion/assets/150902250/2345547c-d1c8-453c-949c-6776aa8f61f2)

If i use the operator "In", i need to augment the  "max_nested_depth" in the orion config. I don't understand, why i should do this.

**Comment by alexzarbn** [comment]
Hi @RulianZB,

Thank you reporting this. To clarify, you encounter this issue only, if `in` operator is used for the `tags.label` field and, if other operators like `=` or `!=` are applied instead, it does not trigger the max depth exception?

**Comment by RulianZB** [comment]
Hi @alexzarbn, yes indeed, if i use the operator = or !=, I have any problems while the error seems to appear only with the in operator

**Comment by alexzarbn** [comment]
@RulianZB,

Okay, thank you for clarifying the issue. I will investigate it further - it seems to be a particularly pesky bug.

**Comment by alexzarbn** [comment]
@RulianZB 

The fix is available as part of the [v2.22.1](https://github.com/tailflow/laravel-orion/releases/tag/2.22.1) release.
