### ISSUE TITLE
Unable to Publish Vendor Config in Laravel-Orion

### ISSUE THREAD

**Issue by alifnuryana** [tailflow/laravel-orion#241]
### Description:
I have installed the latest version of the Laravel-Orion package in my Laravel project. According to the official documentation, there should be an option to publish the vendor config with the name orion-config. However, after the installation completed, I couldn't find the configuration file to publish.

### Steps I Have Taken:

Installed Laravel-Orion's latest version using the composer require command.
Looked for the option to publish the vendor config as per the official documentation.

Results I Experienced:
When attempting to run the command php artisan vendor:publish --tag=orion-config, I received a message indicating that there was nothing to publish.

### Versions I Am Using:

Laravel-Orion: 1.2.9
Laravel Framework: 10.39.0
Documentation Followed:
[[Getting Started in Laravel Orion Docs]](https://tailflow.github.io/laravel-orion-docs/v2.x/guide/getting-started.html#getting-started)

Screenshot (if available):
![image](https://github.com/tailflow/laravel-orion/assets/38722267/35332309-c479-4cba-93d1-2677160f1d88)

I have tried several common solutions, including checking the package directory structure and reading community feedback, but haven't found a solution yet. I would appreciate any assistance in resolving this issue.

Thank you for your attention and help.

**Comment by alexzarbn** [comment]
Hi @alifnuryana,

Please ensure you install the latest version (2.22.1) - there is no config in versions prior to 2.0.
