### ISSUE TITLE
Documentation error: Access level to [Controller]::filterableBy() must be public (as in class Orion\Http\Controllers\BaseController)

### ISSUE THREAD

**Issue by PatFox** [tailflow/laravel-orion#246]
Hi,

A small issue, this one -- the documentation gives the following example code for Controller::filterableBy()

```
protected function filterableBy() : array
    {
        return ['id', 'title', 'user.id', 'meta.source_id', 'created_at'];
    }
```

...which results in an error -- `Access level to [Controller]::filterableBy() must be public (as in class Orion\Http\Controllers\BaseController)`

The same goes for e.g. `exposedScopes()`, `searchableBy()` etc. So the examples should be updated to have these methods set as `public`.

**Comment by alexzarbn** [comment]
Hi @PatFox,

The documentation parts you refer to are for the v1.x, but the latest one is v2.x that has `public` access modifier in both documentation and code.
