### ISSUE TITLE
Custom Resource not working

### ISSUE THREAD

**Issue by ap1969** [tailflow/laravel-orion#247]
Hi,

I'm using Orion for the first time, and cannot get a custom resource to do anything to the output.

My controller is as follows:

```
<?php

namespace Notifium\FilamentEmbedbuilder\Http\Controllers;


use Notifium\FilamentEmbedbuilder\Http\Resources\EmbedbuilderBlockCollectionResource;
use Notifium\FilamentEmbedbuilder\Http\Resources\EmbedbuilderBlockResource;
use Notifium\FilamentEmbedbuilder\Models\EmbedbuilderBlock;
use Orion\Concerns\DisablePagination;
use Orion\Http\Controllers\Controller;

class EmbedbuilderBlocksController extends Controller
{

    use DisablePagination; // Return all records without pagination

    protected $model = EmbedbuilderBlock::class;

    protected $resource = EmbedbuilderBlockResource::class;

    protected $collectionResource = EmbedbuilderBlockCollectionResource::class;

    public function __construct()
    {
        parent::__construct();
        logger("resource", [ "resource" => $this->getResource() ]);
    }

}
```

This correctly logs that $this->getResource() is: 
"resource": "Notifium\\FilamentEmbedbuilder\\Http\\Resources\\EmbedbuilderBlockResource"

The resource is defined as:

```
<?php

namespace Notifium\FilamentEmbedbuilder\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Orion\Http\Resources\Resource;

class EmbedbuilderBlockResource extends Resource
{


    public function __construct($resource)
    {
        parent::__construct($resource);
        logger("Resource created");
    }
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request) : array
    {

        // Set a true/false variable if the created_at date is newer than 1 month
        $new = $this->updated_at->diffInDays(now()) < 30;
        logger("Using resource");
        return [
            'id'       => $this->id,
            'name'     => $this->name,
            'template' => $this->template,
            'config'   => $this->config,
            'new'      => $new,
        ];
    }
}

```

But nothing is logged, so clearly the resource is actually being instantiated.

And the JSON data that the API returns is the full object include created_at, deleted_at, updated_at, etc.

Any help would be greatly appreciated!

Regards.
Andy

**Comment by v-radev** [comment]
Hey @ap1969, are you using the `EmbedbuilderBlockResource` inside the `EmbedbuilderBlockCollectionResource`? Inside the collection I usually declare the `public $collects = ...;` property equal to the single resource and this works for the list of all records. Have you tried calling single item get request or this doesn't work only on the all items endpoint?

**Comment by ap1969** [comment]
Thanks for responding @v-radev 

Weirdly, I just went in to have another try to fix it, and it's working now. Yet I've changed nothing. 

Appreciate your help, anyway.
