### ISSUE TITLE
This action is unauthorized.

### ISSUE THREAD

**Issue by raakkan** [tailflow/laravel-orion#249]
im setup all correctly but unauthorized error returm only orion routes other routes are working.

`

Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');

Route::middleware('auth:sanctum')->group( function() {
    Orion::resource('/languages', LanguageController::class);
});

`

`

class LanguageController extends Controller
{
    protected $model = Language::class;

    protected $resource = LanguageResource::class;

    protected $collectionResource = LanguageCollectionResource::class;

    protected $request = LanguageRequest::class;

    public function resolveUser()
    {
        return Auth::guard('sanctum')->user();
    }
}
`

**Comment by alexzarbn** [comment]
Hi @raakkan,

Do you have any policies setup?
