### ISSUE TITLE
which policy method are use in sync api call

### ISSUE THREAD

**Issue by Shiv9021** [tailflow/laravel-orion#252]
i have uses/{user_id}/role/sync api in orion.
know i want to know which policy method are use in this api (update,delete,etc).
i have UserPolicy and RolePolicy and RoleUserController for this api
api:-    Orion::belongsToManyResource('users', 'roles', RoleUserController::class);
please help me to know which policy method are use for sync api

**Comment by v-radev** [comment]
Hey @Shiv9021, have you tried `update` method on the parent entity policy? There is an example in the docs [here](https://tailflow.github.io/laravel-orion-docs/v2.x/guide/security.html#authorizing-parent-entities) and [here](https://tailflow.github.io/laravel-orion-docs/v2.x/guide/security.html#customizing-policy-classes).

**Comment by Shiv9021** [comment]
my problem are solve thank you for help @v-radev
