### ISSUE TITLE
Illuminate/Foundation dependency is missing

### ISSUE THREAD

**Issue by boywijnmaalen** [tailflow/laravel-orion#26]
Hi,

I'm using this package in combination with Laravel Lumen.
I managed to get it working using very few additions to my own project.

I'm running into an issue where dependency 'illuminate/foundation' is not part of the tailflow/laravel-orion composer.json definition.

If you want I can submit a pull request?

In addition I can create a second pull request on how to use this awesome package with Laravel Lumen? Perhaps update the readme?

Thanks in advance!

**Comment by boywijnmaalen** [comment]
Ah it seems illuminate/foundation is not a package in itself..

**Comment by boywijnmaalen** [comment]
Seems like this package isn't compatible with Lumen, do you agree or am I perhaps missing something?

**Comment by alexzarbn** [comment]
Hi @boywijnmaalen,

Lumen is not officially supported and there is no plan for its support either (PRs are always welcome though).

The reason for that is because nowadays the hardware is powerful enough, so you could get little to no benefit of using Lumen over Laravel.
