### ISSUE TITLE
Documentation is DOWN

### ISSUE THREAD

**Issue by gogl92** [tailflow/laravel-orion#260]
Not sure if it's only me but I cannot access it

<img width="1280" alt="image" src="https://github.com/tailflow/laravel-orion/assets/1505641/77a37b4e-ffe3-4b5d-90b7-ea1c94d2821e">

**Comment by alexzarbn** [comment]
Hi @gogl92,

Thank you for reporting this! I'm preparing a new documentation website and renamed the docs repo which caused GitHub Pages to raise 404. Should be up now.
