### ISSUE TITLE
How to manage versioning

### ISSUE THREAD

**Issue by alberto-bottarini** [tailflow/laravel-orion#267]
I would like to setup some apis for a mobile application.
What is the best approach to manage versioning in order to guarantee retrocompatibility? 
How this will affect open-api spec generation?

Why am I the only one that raise this issue?

**Comment by ndberg** [comment]
The api versioning is already well implemented: [https://orion.tailflow.org/typescript-sdk/configuration#api-prefix)](https://orion.tailflow.org/typescript-sdk/configuration#api-prefix)

And for the backend I use an approach like this: [[laravel-news](https://laravel-news.com/api-versioning-in-laravel-11)](https://laravel-news.com/api-versioning-in-laravel-11)

api-api spec generation works woll

Hope this helps.

**Comment by alberto-bottarini** [comment]
Thank a lot. I was afraid that having versioning "outside" of Orion, spec generation will ignore it.
