### ISSUE TITLE
Automatic Laravel Nova Integration

### ISSUE THREAD

**Issue by dillingham** [tailflow/laravel-orion#27]
When looking at AWS amplify / Google firebase & how they have automatic API support with an admin panel..

Makes me imagine Nova & a fully featured API.. and how this package could maybe fill in that gap.

Like, this package could loop over Nova's resources, relationship fields & construct routes & controllers.

```php
foreach(Nova::resources() as $resource) {

    $controller->model = $resource->model

    foreach($resource->fields() as $field) {
        if($field is hasMany etc) {
            $controller->relation = $field->attribute;
        }
    }
}
```

`php artisan nova:resource Post`, and you have a backend & API

Next all we need is some sort of open api / swagger automagic and we can all quit our jobs.

---

Just posing the idea. Great package btw :)

**Comment by alexzarbn** [comment]
Hi @dillingham,

Thank you ~

I think Laravel Nova already has some sort of automation for API in place (that's basically how it fetches all the data to display model and relationship tables, forms, etc.), but it is internal and not documented.

Eventually, having an adapter for Nova (or perhaps just another level of abstraction for models) that will build all routes/controllers automatically from the given folder (e.g. app/Models) is also something that might be worth looking into. But for now, let's protect ourselves from the possible Skynet invasion 😄
