### ISSUE TITLE
[Feature Request] Fully disable pagination

### ISSUE THREAD

**Issue by PascalHesselink** [tailflow/laravel-orion#29]
In some cases you don't want to use pagination, please add a concern to avoid/disable using pagination.

Such as
```php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Post;
use Orion\Concerns\DisablePagination;
use Orion\Http\Controllers\Controller;

class PostController extends Controller
{
    use DisablePagination;

    protected $model = Post::class;
}
```

**Comment by alexzarbn** [comment]
Hi @PascalHesselink,

Definitely sounds like a valid use-case. Will plan to add this feature ~

**Comment by davigs** [comment]
I also have this need. It would be very interesting to list in selects and components that do not need to be paginated.

**Comment by alexzarbn** [comment]
The ability to [disable pagination](https://tailflow.github.io/laravel-orion-docs/guide/models.html#disabling-pagination) is added in 1.2 release.
