### ISSUE TITLE
Action classes

### ISSUE THREAD

**Issue by axtg** [tailflow/laravel-orion#32]
Hi!

I'm new to APIs, but this package seems pretty cool and structured in its setup.
I have a question though.

Currently, in my LabelController in the store() method, I call a StoreLabelAction. This dedicated single action class invokes the store and returns the Label model. I do this so that whenever I create a label, I have a single class that I can call. Like this:

```
    public function store(LabelRequest $request, StoreLabelAction $action)
    {
        $label = $action->execute($request->validated());

        return response($label, 200);
    }
```

My StoreLabelAction looks like this (simplified):

```
public function execute(array $data) : Label
	{
		if(Label::where('title', $data['title'])->first()) 
		{
			throw new LabelNotUniqueException("Label should be unique.");
		}

		$label = new Label;
		$label->title = $data['title'];
		$label->save();

		return $label;
	}
```

I feel this a clean way of doing so, but following the docs with the performStore() I seem to be lost on how to implement this logic. If at all. What am I missing?

**Comment by axtg** [comment]
For now, I am taking this approach in my LabelController.

```
    protected $storeLabel;

    public function __construct(StoreLabelAction $storeLabel)
    { 
        $this->storeLabel = $storeLabel;
    }

     public function store(Request $request)
    {
        $label = $this->storeLabel->execute($request->all());
        
        return $this->successResponse(201, __('Label created'), $label);
    }
```

Where the StoreLabelAction is unchanged from first post.
Not sure if I'm breaking any conventions here. So still curious to hear how others might approach this use case.

**Comment by axtg** [comment]
I've solved it like this for now.
Just not too happy with switch $request->validated() with $request->all().

```
public function store(Request $request)
    {
        $action = new StoreLabelAction;
        
        $user = $action->execute($request->all());
        
        return $this->successResponse(201, __('Label created'), $label);
    }
```

The StoreLabelAction remains unchanged.

**Comment by alexzarbn** [comment]
Hi @axtg,

The current implementation of Laravel Orion does not have a concept of "actions". Trying to make it work with this concept will not result in a clean and working solution, unless it is supported on the package level.

If you would like to customize the behavior of queries, please check the [Customizing Queries](https://tailflow.github.io/laravel-orion-docs/guide/models.html#setting-up-routes) section of the docs.

It is also possible (and actually recommended) to put any additional business logic in [Hooks](https://tailflow.github.io/laravel-orion-docs/guide/hooks.html#on-model-controllers). How that logic is orchestrated and executed there is solely app's (developer's) responsibility - Laravel Orion just provides a tooling to accomplish this.
