### ISSUE TITLE
Model resolution for Relationships fail when using explicit binding

### ISSUE THREAD

**Issue by ibrahim-mubarak** [tailflow/laravel-orion#38]
When using relationship controllers, the model resolution fails when using explicit binding as mentioned here
https://laravel.com/docs/8.x/routing#explicit-binding

The following implementation works around it and uses laravel's internal route resolution logic and should theoretically work with slugs as well. This is only an example and I'm aware we need to update this in a lot of places

```php
    protected function runParentFetchQuery(Request $request, Builder $query, $parentKey): Model
    {
        if ($parentKey instanceof $this->model) {
            return $parentKey;
        }

        /** @var Model $modelClass */
        $modelClass = $this->getModel();
        return (new $modelClass())->resolveRouteBinding($parentKey);
    }
```

**Comment by alexzarbn** [comment]
Hi @ibrahim-mubarak,

Laravel Orion is not using explicit route model binding and never will - logic for retrieving models is encapsulated in the dedicated methods on controllers and can be [customized](https://tailflow.github.io/laravel-orion-docs/guide/models.html#customizing-queries).
