### ISSUE TITLE
The given data was invalid

### ISSUE THREAD

**Issue by derrickkorku** [tailflow/laravel-orion#40]
I am getting the error, "The given data was invalid.", on get requests.

**Comment by alexzarbn** [comment]
Hi @derrickkorku,

Please share the complete url for the endpoint you are trying to access.

**Comment by derrickkorku** [comment]
@alexzarbn I have been able to solve the problem. My request class was still extending the default Laravel FormRequest. I had to change it to extend your Orion Request class. Perhaps the documentation should make it clear that clear.
