### ISSUE TITLE
[Feature Request] Support for nested relation routes

### ISSUE THREAD

**Issue by xel-x** [tailflow/laravel-orion#43]
### What and Why

Laravel supports [restful-nested-resources](https://laravel.com/docs/5.1/controllers#restful-nested-resources), which are configured by chaining them with dots.

Their behaviour is already partially supported with all those great relation-routes, but they only support one level of nesting/relation.

As I need another nesting level I tried using laravels dot notation, which did work partially, which is even worse than failing all together, as the results look correct, but are simply wrong.

### Adding Routes works fine

I am adding new routes like:
```
Orion::belongsToManyResource('as.bs','cs', \App\Http\Controllers\Api\BCController::class);
```
which creates the expected routes like:

| Method    | URI                                                   | Name                              | Action                                                                    |
|-----------|-------------------------------------------------------|-----------------------------------|---------------------------------------------------------------------------|
| GET/HEAD  | api/as/{a}/bs/{b}/cs               | as.bs.cs.index         | App\Http\Controllers\Api\BCController@index                       |
| POST      | api/as/{a}/bs/{b}/cs               | as.bs.cs.store         | App\Http\Controllers\Api\BCController@store                       |
| ...      | ...        | ...        | ....                      |
| GET/HEAD  | api/as/{a}/bs/{b}/cs/{c?}       | as.bs.cs.show          | App\Http\Controllers\Api\BCController@show                        |
| PUT/PATCH | api/as/{a}/bs/{b}/cs/{c?}       | as.bs.cs.update        | App\Http\Controllers\Api\BCController@update                      |
| ...   | ...       | ...       | ...                     |

(I am not sure why the c is marked optional, but thats not the point)

##### Expected Result
Listing of all Cs of B2 (given B2 is related to A1)

##### Real Result
Listing of all Cs of B1 (even if B1 is not related to any A)

##### Expected Result
C3 (given C3 is related to B2 and B2 is related to A1)

##### Current Result
C2 (with C2 being related to B1)

#### Further expectations

I'd expect the APolicy to be checked too, but it doesn't seem to be.

### Cheers

I am a bit sad for the controller not working out of the box and me having to try getting it to work as expected or writing it myselfe by hand again -- but thats just because of how awesome orion is and how much time it did save me at all the other controllers, which did work just out of the box. Great work - so much appreciated!

**Comment by xel-x** [comment]
I managed to get my Controller to do as I'd expect. It's not 100% tested, but it seems to do the trick in my simple cases.
I wrote it so it could possibly be used with virtually infinite nesting, so maybe it could be used as a starting point for an implementation or maybe at least help someone...

```php
<?php

namespace App\Http\Controllers\Api;

use App\Models\A;
use App\Models\B;
use Orion\Http\Controllers\RelationController;
use Orion\Http\Requests\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class BCController extends RelationController
{
    protected $model = B::class;

    protected $relation = 'cs';

    private $relationChain = [
        ['url_name' => 'a', 'class' => A::class, 'relation' => 'bs']
    ];

    private function getParentKey(Request $request) {
        return $request->route('b');
    }

    private function getRelatedKey(Request $request) {
        return $request->route('c');
    }

    private function checkRelationChain(Request $request) {
        $child = $this->getParentKey($request);
        foreach($this->relationChain as $relation) {
            $pkey = $request->route($relation['url_name']);
            if(!$pkey) throw new NotFoundHttpException();
            $parent = $relation['class']::query()->findOrFail($pkey);
            $parent->{$relation['relation']}()->findOrFail($child);
            $this->authorize('view', $parent);
            $child = $parent->id;
        }
    }

    public function index(Request $request, $parentKey)
    {
        $this->checkRelationChain($request);
        return parent::index($request, $this->getParentKey($request));
    }

    public function store(Request $request, $parentKey) {
        $this->checkRelationChain($request);
        return parent::store($request, $this->getParentKey($request));
    }

    public function show(Request $request, $parentKey, $relatedKey = null) {
        $this->checkRelationChain($request);
        return parent::show($request, $this->getParentKey($request), $this->getRelatedKey($request));
    }

    public function update(Request $request, $parentKey, $relatedKey = null) {
        $this->checkRelationChain($request);
        return parent::update($request, $this->getParentKey($request), $this->getRelatedKey($request));
    }

    public function destroy(Request $request, $parentKey, $relatedKey = null) {
        $this->checkRelationChain($request);
        return parent::destroy($request, $this->getParentKey($request), $this->getRelatedKey($request));
    }

    public function restore(Request $request, $parentKey, $relatedKey = null) {
        $this->checkRelationChain($request);
        return parent::restore($request, $this->getParentKey($request), $this->getRelatedKey($request));
    }

    public function attach(Request $request, $parentKey) {
        $this->checkRelationChain($request);
        return parent::attach($request, $this->getParentKey($request));
    }

    public function detach(Request $request, $parentKey, $relatedKey = null) {
        $this->checkRelationChain($request);
        return parent::detach($request, $this->getParentKey($request));
    }

    public function sync(Request $request, $parentKey, $relatedKey = null) {
        $this->checkRelationChain($request);
        return parent::sync($request, $this->getParentKey($request));
    }

    public function toggle(Request $request, $parentKey, $relatedKey = null) {
        $this->checkRelationChain($request);
        return parent::toggle($request, $this->getParentKey($request));
    }

    public function updatePivot(Request $request, $parentKey, $relatedKey = null) {
        $this->checkRelationChain($request);
        return parent::updatePivot($request, $this->getParentKey($request), $this->getRelatedKey($request));
    }

    public function batchStore(Request $request, $parentKey, $relatedKey = null) {
        $this->checkRelationChain($request);
        return parent::batchStore($request, $this->getParentKey($request));
    }

    public function batchUpdate(Request $request, $parentKey, $relatedKey = null) {
        $this->checkRelationChain($request);
        return parent::batchUpdate($request, $this->getParentKey($request));
    }

    public function batchDestroy(Request $request, $parentKey, $relatedKey = null) {
        $this->checkRelationChain($request);
        return parent::batchDestroy($request, $this->getParentKey($request));
    }
}
```

**Comment by alexzarbn** [comment]
Hi @xel-x,

Thank you for sharing this!

Currently there are no plans to support deeply nested routes, simply because most of the time using just 2 levels is enough. 

For example, consider the following route:

`(GET) /api/users/1/posts/1/comments/3`

There are 3 levels, but essentially, we need to retrieve the comment, right? It can be simplified to the following:

`(GET) /api/posts/1/comments/3`

Whether a user is able to retrieve a specific comment or not - it is the job of a related policy.

**Comment by xel-x** [comment]
While I understand your decision, I wanted to clarify my intention:

It's not because of right management or something, its because of meaning and intuitive APIs.

Say we got companies, branches and announcements (associated to the branches).

Our API could be flat like
```
/api/companies
/api/companies/{company}
/api/branches
/api/branches/{branch}
/api/announcements
/api/announcements/{announcement}
```

As long as the relations aren't many-to-many even relation management would be technically possible. Not nice, but possible.
Much nicer it does work with the following, which Orion supports:

```
/api/companies
/api/companies/{company}
/api/companies/{company}/branches
/api/companies/{company}/branches/{branch}
/api/branches/{branch}/announcements
/api/branches/{branch}/announcements/{announcement}
```

Technically that does the trick and works.
But it feels awkward and unintutive for me, which was my reasoning for adding another level.
This way it feels like there is a `/api/branches/` and a `/api/branches/{branch}` route missing. Adding them would be possible, but somewhat redundant -- and probably even problematic as the listing couldn't be filtered by policies.

The following would feel "natural" and complete for me, while not adding any redundance.

```
/api/companies
/api/companies/{company}
/api/companies/{company}/branches
/api/companies/{company}/branches/{branch}
/api/companies/{company}/branches/{branch}/announcements
/api/companies/{company}/branches/{branch}/announcements/{announcement}
```

But that might just be personal preference - others might argue it would be better to reduce the amount of information needed for every route.

Thank you for your time and all the effort you put into Orion, it's awesome.

**Comment by rizaldywirawan** [comment]
I hope this feature can be implemented.
