### ISSUE TITLE
Does "Request" have to be an instance of "Orion\Http\Requests\Request"?

### ISSUE THREAD

**Issue by ldiebold** [tailflow/laravel-orion#45]
When hitting an Orion index route, I'm getting the error:

```
Argument 1 passed to Orion\\Http\\Controllers\\Controller::index() must be an instance of Orion\\Http\\Requests\\Request
```

Does this mean that we are unable to use laravels `Illuminate\Foundation\Http\FormRequest` class for requests?

If not, that's totally fine! Might just need to add that to the docs here:
[https://tailflow.github.io/laravel-orion-docs/guide/security.html#authentication](url)

**Comment by ldiebold** [comment]
It might be a good idea to have an artisan command for requests:
`php artisan orion:request` or something like that!

**Comment by alexzarbn** [comment]
Hi @ldiebold,

Yes, Request classes must extend `Orion\Http\Requests\Request`. It is, in fact, a normal `Illuminate\Foundation\Http\FormRequest`, just with a sprinkle of Orion methods for resolving validation rules of relation specific endpoints.

I have added a note about this to the [Validation](https://tailflow.github.io/laravel-orion-docs/guide/security.html#validation) and [Getting Started](https://tailflow.github.io/laravel-orion-docs/guide/getting-started.html#simple-crud) sections.

**Comment by ldiebold** [comment]
Perfect. Thanks @alexzarbn
