### ISSUE TITLE
Soft Deletes seem to return the entire model for the key

### ISSUE THREAD

**Issue by ldiebold** [tailflow/laravel-orion#47]
When using soft deletes, I'm getting the following error:
```
"message": "No query results for model [App\\User].",
"exception": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
"file": "/var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php",
"line": 222
```
I have a clue as to why.

In `HandlesStandardOperations.php` the method `restore` seems to be returning the whole model for the **key** instead of just the id. Haven't managed to track down why that is yet, need to do a little more source diving!

To test my theory, I added the following to the top of the `restore` method and it worked:

`HandlesStandardOperations.php`
```php
   ...

    public function restore(Request $request, $key)
    {
        $key = $key->id; // <<<<<
        $requestedRelations = $this->relationsResolver->requestedRelations($request);

        $query = $this->buildRestoreFetchQuery($request, $requestedRelations);
        $entity = $this->runRestoreFetchQuery($request, $query, $key);

      ...
   }
```

**Comment by alexzarbn** [comment]
Hi @ldiebold,

Hmm, that's an interesting one. Do you have any model bindings in place?

**Comment by ldiebold** [comment]
Believe I do. Will be home soon and check, thanks for the fast reply!

**Comment by ldiebold** [comment]
You were right @alexzarbn. I messed with the model binding and really shouldn't have.
In case somebody comes across this, I had the following in `RouteServiceProvider.php`

```php
Route::bind('user', function ($id) {
    return User::withTrashed()->findOrFail($id);
});
```

Removing this line fixed it for me!
