### ISSUE TITLE
How to disable policy for a specific endpoint

### ISSUE THREAD

**Issue by ldiebold** [tailflow/laravel-orion#49]
Is it currently possible to disable policy checks for a given endoint?

My use case is for indexing users. When I hit `api/users`
- an **admin** will get all users
- a **manager** will get users they manage
- a **plain user** will only get themself

However, I don't want to set my `viewAny` policy to `return true;` because that feels a bit risky.

...

I may be asking for too much... Honestly, this extension is an absolute dream. I've spent the last 4 days converting our entire API to orion because the benefits are insane!

**Comment by alexzarbn** [comment]
Hi @ldiebold,

Normally, I set `viewAny` to return `true`, and add constraints to the query (the `WHERE user_id IN ...` part) - policies cannot influence the queries anyway.

In fact, I rarely find myself relying on `viewAny`, unless there is a need to literally prohibit viewing a list of resources 🤔

It's incredible to hear that existing APIs are being converted to Orion 😃

**Comment by alexzarbn** [comment]
@ldiebold Please let me know, if that requires further discussion. Otherwise, the issue should be closed, I think.
