### ISSUE TITLE
Support for null filters

### ISSUE THREAD

**Issue by ibrahim-mubarak** [tailflow/laravel-orion#50]
How would we go about implementing null filters

```
{
	"filters": [{
			"field": "created_at",
			"operator": ">=",
			"value": "2021-02-01"
		},
		{
			"field": "created_at",
			"operator": "<=",
			"value": "2021-02-28"
		},
		{
			"field": "category_id",
			"operator": "=",
			"value": null
		}
	]
}
```

This throws the following error
"The filters.2.value field is required when filters is present."

**Comment by alexzarbn** [comment]
Hi @ibrahim-mubarak,

Thanks for the heads-up! Fixed in [v1.2.4](https://github.com/tailflow/laravel-orion/releases/tag/1.2.4).
