### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by AEK-BKF** [tailflow/laravel-orion#52]
Hello,

Could you please provide us an example for how to do a custom search.
How to to pass parameters via axios for example. (I'm using Nuxt Js)
 
Thanks

**Comment by alexzarbn** [comment]
Hi @AEK-BKF,

There is an [entire section](https://tailflow.github.io/laravel-orion-docs/guide/search.html#filtering) in the documentation covering the search functionality - please take a look there.
