### ISSUE TITLE
ErrorHandler

### ISSUE THREAD

**Issue by rbayley** [tailflow/laravel-orion#58]
Hi, 
I have been using your package for the last 24hs and I love it already. It completely changes the way of building APIs.

I am having trouble when trying to GET, PUT|PATCH or DELETE  an either soft|forced deleted record.
I get a 404 response with **NotFoundHttpException** error page.
How can I prevent this and send a specific json response with whatever error message in it?

Thank you very much for your help and awesome package!!

**Comment by alexzarbn** [comment]
Hi @rbayley,

Have you tried applying [query parameters](https://tailflow.github.io/laravel-orion-docs/guide/query-parameters.html#soft-deletes) specific to the Soft Deletable resources?

**Comment by rbayley** [comment]
Hi Alex,

Yes, I did, that's why I am able to soft delete and force delete the record.

The problem is when trying to GET or UPDATE the record **after** it has been soft or forced deleted. Record no longer exists and therefore Laravel replies with an error.

In other words,  Laravel throws an Exception when fetching an inexistent record.

**Comment by alexzarbn** [comment]
@rbayley

If you are looking to customize how errors are returned in the response, I believe checking the `render` method in `App\Exceptions\Handler` and `Illuminate\Foundation\Exceptions\Handler` might be a good idea 🤔

**Comment by rbayley** [comment]
@alexzarbn ouch !

I thought you might be throwing specific errors. Next time I will dig more into your code. But yeah, its the logical way.
After posting my question, I thought you would come up with something like that! 😢 

Once again, great, great package!

**Comment by alexzarbn** [comment]
@rbayley 

404 is already a specific error, throwing something else would be a violation of many standards, I think.
