### ISSUE TITLE
Support for Laravel JSON Where Clauses

### ISSUE THREAD

**Issue by gech4me** [tailflow/laravel-orion#6]
How to filter JSON attributes?
I need support for JSON Where 
Link: [https://laravel.com/docs/8.x/queries#json-where-clauses](https://laravel.com/docs/8.x/queries#json-where-clauses)

**Comment by alexzarbn** [comment]
Hi @gech4me,

It is currently not possible to filter json columns, but I will look into implementing this in the coming weeks.

**Comment by alexzarbn** [comment]
A small update on this one - the support for json columns is planned for 1.3 release.

**Comment by gech4me** [comment]
> A small update on this one - the support for json columns is planned for 1.3 release.

That's good. Keep up the good work!

**Comment by jnorms** [comment]
are there any plans to release version 1.3?

**Comment by alexzarbn** [comment]
Hi @jnorms,
 
 Of course, currently all efforts are focused on getting Typescript SDK released. Once that is done, I will continue working on new releases of the package itself.

**Comment by jnorms** [comment]
@alexzarbn do you need collaborators on the project? If so, I may be helping!

**Comment by alexzarbn** [comment]
@jnorms I am definetely open for any PRs ✌️

**Comment by alexzarbn** [comment]
The feature is now available as part of the [v2.0 release](https://github.com/tailflow/laravel-orion/releases/tag/2.0.0) 🎉
