### ISSUE TITLE
Argument 3 passed to Orion\\Http\\Controllers\\Controller::performUpdate() must be of the type array, null given

### ISSUE THREAD

**Issue by PaulUgwu** [tailflow/laravel-orion#60]
Hello, am trying to use the laravel orion batch update functionality. it works fine on default but when i use change the **keyName** to slug it gives error "Argument 3 passed to Orion\\Http\\Controllers\\Controller::performUpdate() must be of the type array, null given" what am i doing wrong?

am using postman for testing, bellow is my postman setup

Body -> row -> json

{
    "resources": {
        "nigeria": {
            "description": "new description"
        },
        "gambia": {
            "description": "new description"
        }
    }
}

URL: Patch -> http://elo.test/api/countries/batch

**Comment by PaulUgwu** [comment]
My issues is that batch update only worker when keyName() returns "Id"

**Comment by alexzarbn** [comment]
Hi @PaulUgwu,

Looks like a bug in batch operations. Let me run some checks, and I will get back to you.

**Comment by alexzarbn** [comment]
@PaulUgwu,

You also need to change the key type on the model like so
```php
protected $keyType = 'string';
```
