### ISSUE TITLE
Unexpected behaviour in Search Query 

### ISSUE THREAD

**Issue by SachinGanesh** [tailflow/laravel-orion#61]
I have a search query with filter and sort applied as shown below. This endpoint was working fine before and I started getting an empty response even though there are valid records in the DB. Even the total count in the response was correct. 
This issue was appearing only when using the sort filter. I updated one of the record and I started getting the results again. I'm not able to reproduce this issue.

What might be the issue here?  

<img width="1494" alt="Orion search" src="https://user-images.githubusercontent.com/11994640/109458565-0fd73a80-7a83-11eb-9344-3d8fd14d59c6.png">

**Comment by alexzarbn** [comment]
Hi @SachinGanesh,

This is an interesting one. Could you please provide more details on what updated you have made to the record(s)?

**Comment by SachinGanesh** [comment]
If I remember correctly, the sorting key "pages" had the same value in all records. I changed the "pages" value in one of the records and I got the expected results.

**Comment by SachinGanesh** [comment]
Okay. I got to know why I'm not getting any results. SQL query fails because of the following error 

> **SQL Error [1038] [HY001]: Out of sort memory, consider increasing server sort buffer size**

This is because I have large JSON data attached to each record. I have fixed it by writing a custom query instead of using a query filter. 
This issue is no related to Orion. But instead of empty results, shouldn't we get an error if the query fails?

**Comment by SachinGanesh** [comment]
Looks like Laravel is not throwing any exception when the query fails
```php
try {
     $response->data = Record::where('book_iad', "01ezmbnbbayjmxe6shmp58zjk7")->where('is_published', true)->orderByDesc('version')->first();
} catch (Exception $e) {
     dd($e->getMessage());
}
```
