### ISSUE TITLE
route model binding has a 32 character limit

### ISSUE THREAD

**Issue by ldiebold** [tailflow/laravel-orion#62]
This is not an issue with orion. However, orion might be able to implement a solution to this error.

When using route model binding (as orion does behind the scenes), the name of the model cannot be more than 32 characters long.

The following will not work when creating a laravel route:
```
Route::get('very_long_route_name/{very_long_model_name_will_not_work_with_model_binding}', [SomeController::class, 'show');
```

I remember looking into this issue in the past, and it looks like Laravel doesn't intend on fixing this... It's actually because of a limitation in symfony.

Would it be possible to add something like `modelBindingName('short_model_name')` so that we can avoid this "32 character" limit?

Thanks for all your hard work!

**Comment by alexzarbn** [comment]
Hi @ldiebold,

Laravel Orion does not use route model binding - instead, it relies directly on QueryBuilder, giving the ability to [customize](https://tailflow.github.io/laravel-orion-docs/guide/models.html#customizing-queries) the underlying queries in the controller.

In general, I think this limitation makes sense - an app shouldn't have models with such long names 🤔

**Comment by ldiebold** [comment]
Oh you're right, the issue seems to have disappeared, must have been a false positive.

My bad!
