### ISSUE TITLE
Search in relationship with multiple databases.

### ISSUE THREAD

**Issue by szmass** [tailflow/laravel-orion#64]
Hi!

As far as I understand, there's no way to search in relations in different databases. When the QueryBuilder class applies the search to the query builder it uses the whereHas query builder function, but there's no way to specify another connection for the relation if needed.
I stand corrected if I'm wrong :)

**Comment by alexzarbn** [comment]
Hi @szmass,

Yes, the query builder is basically equal to calling `Model::query()` (with whatever connection it is using).

What is the use case for querying relations from another connection?

**Comment by szmass** [comment]
Hi @alexzarbn,

I'm developing an application with multitenant database and the some landlord database entities has relation to the tenant databases entities.
For now, I defined scopes for these cases, because there I can define the connection of the relation in the model function.

**Comment by alexzarbn** [comment]
Oh, that makes sense! Currently, there is no support for multi tenancy, though you could (as mentioned, define scopes, etc.) find some workarounds for this.
