### ISSUE TITLE
Request rules method is triggered on index method

### ISSUE THREAD

**Issue by Staedion** [tailflow/laravel-orion#66]
The request rules method is triggered on the controllers' index method, which will result in validation rules evaluated on http get requests, resulting in an invalid data message. This is undesirable behavior.

**Comment by syahnur197** [comment]
I think you should type hint your request classes at beforeSave, beforeStore, beforeUpdate methods. 

Can see [more here](https://tailflow.github.io/laravel-orion-docs/guide/hooks.html#hooks)

**Comment by Staedion** [comment]
@syahnur197 what will be the result of that? The request's rule method will be evaluated before that resulting in evaluating vildation rules on index method.

**Comment by syahnur197** [comment]
by typehinting in the methods I mentioned above, you the form request class will only be executed when you are invoking save, update, stored method

**Comment by Staedion** [comment]
@syahnur197  Did you test this? Can you provice me with some example code? Type hinting gives me an error, when following documentation nothing changes. Rules are still fired in index.

**Comment by alexzarbn** [comment]
Hi @Staedion,

Please check the [docs](https://tailflow.github.io/laravel-orion-docs/guide/security.html#validation) - validation topic is covered there.
