### ISSUE TITLE
use if statement in search query

### ISSUE THREAD

**Issue by goldjunge4** [tailflow/laravel-orion#67]
Hello,

Would it be possible (maybe allready) to perform an if in the search function?

```
public function scopeToday($query)
    {
        if ($query->select('dkfertzu_prod_nr', 'dkfertzu_menge', 'dkfertzu_erfdat', 'dkfertzu_erfzeit','finished_lot','rework_part','failure_part','prod_group')->where('store_area','EMA')->where('dkfertzu_erfdat',Carbon::today()->format('d.m.Y'))->count()==0)
        {
            return $query->select('dkfertzu_prod_nr', 'dkfertzu_menge', 'dkfertzu_erfdat', 'dkfertzu_erfzeit','finished_lot','rework_part','failure_part','prod_group')->where('store_area','EMA')->first();
        }
        else
        {
            return $query->select('dkfertzu_prod_nr', 'dkfertzu_menge', 'dkfertzu_erfdat', 'dkfertzu_erfzeit','finished_lot','rework_part','failure_part','prod_group')->where('store_area','EMA')->where('dkfertzu_erfdat',Carbon::today()->format('d.m.Y'));
        }

    }
```

**Comment by alexzarbn** [comment]
Hi @goldjunge4,

No, it is currently not possible to create conditional search queries. I would suggest (at least for now) to do that via scopes just like in the provided example.

**Comment by goldjunge4** [comment]
> Hi @goldjunge4,
> 
> No, it is currently not possible to create conditional search queries. I would suggest (at least for now) to do that via scopes just like in the provided example.

Hello Alex, thanks for the information but my example above is not working, could you help me to adjust it correctly? Thanks
