### ISSUE TITLE
Batch destroy for trashed

### ISSUE THREAD

**Issue by 1c3f0x84** [tailflow/laravel-orion#69]
Hello, 

i have a problem, i can't batch destroy trashed entities. 

The call: .../batch?force=true&only_trashed=true 
With body: {resources: [9]}

It seem to me that "only_trashed=true" is ignored.

Can someone help me with this?

Sincerly

**Comment by alexzarbn** [comment]
Hi @1c3f0x84,

Let me try to replicate this behaviour locally, and I will get back to you as soon as I have a clear picture of the issue.

**Comment by alexzarbn** [comment]
Hi @1c3f0x84,

Thank you for reporting this. I was able to replicate the issue locally and fixed it in [v1.2.6](https://github.com/tailflow/laravel-orion/releases/tag/1.2.6) release.
