### ISSUE TITLE
Retrieve grandchildren on morphTo

### ISSUE THREAD

**Issue by antandev** [tailflow/laravel-orion#72]
hello, i have morphTo relationship and one of them relationship with another model like example below.

```
Model A
  contentable - morphTo B & C

Model B
  A - morphOne

Model C
  A - morphOne
  D - belongsToMany

Model D
  C - belongsToMany
```

to retrieve model B and C when model A is called i can use `alwaysIncludes` on controller, but i cannot retrieve model D because model B does not associate with model D

the only way to retrieve model D is using [nested-lazy-eager-loading-morphto](https://laravel.com/docs/8.x/eloquent-relationships#nested-lazy-eager-loading-morphto).

how to implements it on controller ? i have tried to use it on runIndexFetchQuery, runFetchQuery, afterIndex but model D does not show up

**Comment by alexzarbn** [comment]
Hi @antandev,

Could you please share the implementation of `includes` and `alwaysIncludes` methods from the controller?

**Comment by antandev** [comment]
my controller was something like this

```
class AController extends Controller
{
    protected $model = A::class;

    protected function alwaysIncludes(): array
    {
        return ['B', 'C', 'B.D'];
    }
}
```

**Comment by alexzarbn** [comment]
@antandev,

- Check if `C` model class has a relationship method named `D` (case sensitive)
- Check if relationship `D` is actually loaded (dump the results inside `runFetchQuery` using `$query->get())`)
- In `alwaysIncludes` add `contentable.D`

**Comment by antandev** [comment]
@alexzarbn 

already did 3 points the above and everything is fine but this message always show up

`Call to undefined relationship [D] on model [App\\Models\\B].`

**Comment by antandev** [comment]
hi @alexzarbn, i already found the solution, my solution was:
1. remove `contentable` and its child from `alwaysIncludes`
2. changing `loadMorph` to `morphWith`, this way the code will return query instead collection
3. implement it on `buildFetchQuery` instead on `runFetchQuery` or `runIndexFetchQuery`

```
    protected function alwaysIncludes(): array
    {
        return ['A'];
    }

    protected function buildFetchQuery(Request $request, array $requestedRelations): Builder
    {
        ...

        return $this->queryBuilder->buildQuery($this->newModelQuery(), $request)->with(array_merge($this->alwaysIncludes(),['contentable' => function (MorphTo $morphTo) {
            $morphTo->morphWith([
                B::class,
                C::class => ['D']
            ]);
        }]));
    }
```

thank you for your help this couple days, it was really awesome to have someone like you helping others.

**Comment by antandev** [comment]
hi @alexzarbn, i already found the solution, my solution was:
1. create 1 variable to store default eager loading which to be used when there is a situation like this one
2. add `contentable` child to `alwaysIncludes`
3. changing `loadMorph` to `morphWith`, this way the code will return query instead collection
4. implement it on `buildFetchQuery` instead on `runFetchQuery` or `runIndexFetchQuery`

```
    private $with = ['contentable'];

    protected function alwaysIncludes(): array
    {
        return array_merge($this->with, ['contentable.D']);
    }

    protected function buildFetchQuery(Request $request, array $requestedRelations): Builder
    {
        ...

        return $this->queryBuilder->buildQuery($this->newModelQuery(), $request)->with(array_merge($this->with,['contentable' => function (MorphTo $morphTo) {
            $morphTo->morphWith([
                B::class,
                C::class => ['D']
            ]);
        }]));
    }
```

thank you for your help this couple days, it was really awesome to have someone like you helping others.
