### ISSUE TITLE
Pass parent model to hook methods in relationship controllers

### ISSUE THREAD

**Issue by oscar-parra** [tailflow/laravel-orion#73]
in relationship controllers, the hooks should allow access to parent model

thanks for laravel orion, great job

**Comment by alexzarbn** [comment]
Hi @oscar-parra,

Indeed, it would be quite useful to have direct access to parent model from inside the hook methods. Scheduled for v2.0 ✨

**Comment by alexzarbn** [comment]
The feature is now available as part of the [v2.0 release](https://github.com/tailflow/laravel-orion/releases/tag/2.0.0) 🎉
