### ISSUE TITLE
File Uploads

### ISSUE THREAD

**Issue by suman-bonakurthi** [tailflow/laravel-orion#75]
Currently, I am using Laravel Orion for my resources, but I am not able to upload images. Is there any work around or guide me, how to use . Many thanks.

**Comment by alexzarbn** [comment]
Hi @suman-bonakurthi,

You can use something like [spatie/laravel-medialibrary](https://github.com/spatie/laravel-medialibrary).

**Comment by suman-bonakurthi** [comment]
Hi @alexzarbn, thanks for your reply. Currently I am using Spatie Media Library. My question is, whether Laravel Orion has inbuilt support for File Upload to store, upload? 

For Example, I have a Table 
            $table->id();
            $table->string('title')->unique()->comment('Accrual Title');
            $table->string('label')->comment('Label of Accrual');
            $table->string('description')->nullable()->comment('Accrual Description');

This is the Request Class

            'title' => 'required|unique:accruals|string|min:3|max:25',
            'label' => 'required|image',
            'description' => 'sometimes|string|min:5|max:50',

Can I simply use the Orion Controller for CRUD?
Unfortunately, when I test, it doesn't support, So, I am asking a work around or best pracitce.

Any Help will be highly appreciated.
