### ISSUE TITLE
Image Uploads

### ISSUE THREAD

**Issue by suman-bonakurthi** [tailflow/laravel-orion#76]
Hi @alexzarbn, thanks for your reply. Currently I am using Spatie Media Library. My question is, whether Laravel Orion has inbuilt support for File Upload to store, upload?

For Example, I have a Table
```
$table->id();
$table->string('title')->unique()->comment('Accrual Title');
$table->string('label')->comment('Label of Accrual');
$table->string('description')->nullable()->comment('Accrual Description');
```

This is the Request Class

       ```
 'title' => 'required|unique:accruals|string|min:3|max:25',
        'label' => 'required|image',// The file is of type image.
        'description' => 'sometimes|string|min:5|max:50',
```
Can I simply use the Orion Controller for CRUD?
Unfortunately, when I test, it doesn't support, So, I am asking a work around or best pracitce.

Any Help will be highly appreciated.

**Comment by SachinGanesh** [comment]
You can do something like this with [Hooks](https://tailflow.github.io/laravel-orion-docs/guide/hooks.html#on-model-controllers) in your controller
```php
    protected function afterSave(Request $request, $model)
    {
        if ($request->hasFile('label') && $request->file('label')->isValid()) {
            $model->addMedia($request->file('label'))->toMediaCollection('default');
        }
    }
```

**Comment by alexzarbn** [comment]
@suman-bonakurthi,

Laravel Orion is built on top of standard Laravel functionality (Requests, Policies, etc.) - it supports everything that Laravel itself supports 🙂 

How you orchestrate file uploading logic in controllers is up to you and your app business requirements.

@SachinGanesh has provided a good example of how it can be accomplished using hook method.
