### ISSUE TITLE
Config option to select only to use validated inputs

### ISSUE THREAD

**Issue by 1c3f0x84** [tailflow/laravel-orion#77]
Hi,

i would like to have an option to only save "$request->validated()" values and not everything.

Is that possible?

Ps: Keep up the good work!

**Comment by alexzarbn** [comment]
Hi @1c3f0x84,

Currently all request data is passed to model constructor, so it just relies on the `$fillable` and/or `$guarded` properties of the model. What is the use case when you would want only validated properties to be processed and marking other properties as non-fillable would not provide the desired outcome?

**Comment by josecl** [comment]
Hi, I have same need.

Some scenarios:
- I define different rules for store and update: I want to enforce some attributes only when creating, but prevent modification on update.
- Sometimes I rely in Gates to define validation rules depending if the current user is admin or not. For regular users I don´t give them access to some attributes.

**Comment by jonagoldman** [comment]
Same here, I set `$guarded = []` and rely only on `$request->validated()`.
Laravel core member [Mohamed Said](https://twitter.com/themsaid) explains why in this [Don't use mass assignment protection](https://www.youtube.com/watch?v=XNy0hldKHjM) video.

**Comment by alexzarbn** [comment]
Hi @josecl, @jonagoldman

Seems like a valid use-case, in the next releases I will look into providing different strategies for filling out the attributes 👌

**Comment by jonagoldman** [comment]
A workaround is to use the `beforeSave` [hook](https://tailflow.github.io/laravel-orion-docs/guide/hooks.html) to replace the request values with only the values that have rules.

```php
use Orion\Http\Requests\Request;
use Orion\Http\Controllers\Controller;

class BaseController extends Controller
{
    protected function beforeSave(Request $request, $entity)
    {
       $request->replace($request->only(array_keys($request->rules())));
    }
}
```

This will remove from the request any value that doesn't have a rule.

**Comment by alexzarbn** [comment]
Hi @josecl @jonagoldman,

I have added `performFill` method - it can be used to override the default logic, instead of overriding each and every `performStore` & `performUpdate` methods. This way it is more flexible than a config option and requires only a single change in a base controller.
