### ISSUE TITLE
Is the resourceAbilityMap method override needed?

### ISSUE THREAD

**Issue by jonagoldman** [tailflow/laravel-orion#80]
Not really a bug, but is there a reason to override the `resourceAbilityMap` method from the `AuthorizesRequests` trait?
https://github.com/tailflow/laravel-orion/blob/c03e9d618215b63bb0ea70d05242fb6a696b2399/src/Http/Controllers/BaseController.php#L189-L200

**Comment by alexzarbn** [comment]
Hi @jonagoldman,

As far as I remember, it was done because previous versions of Laravel were missing the mapping of `index` method to `viewAny`.  In the future version, when support for Laravel 5.7 will be dropped, this override won't be required anymore.
