### ISSUE TITLE
is it possible to always include a nested has_many from many to many?

### ISSUE THREAD

**Issue by musixite** [tailflow/laravel-orion#83]
- section belongsToMany collections
- collection belongsToMany sections
- collections hasMany bookmarks

I created a SectionCollections database
```
class SectionCollectionsController extends RelationController
{
    protected $model = Section::class;
    protected $pivotFillable = ['position'];
    protected $relation = 'collections';

}
```

This works well but I'd like to retrieve the bookmarks relationship from the collections.

I tried by adding
```
    protected function alwaysIncludes(): array
    {
        return ['collections.bookmarks];
    }
```

... but this doesn't work!

Any ideas?

**Comment by alexzarbn** [comment]
Hi @musixite,

If you call `Section::query()->with('collections.bookmarks')->get()`, do the bookmarks show up?
