### ISSUE TITLE
invalid json response with null 

### ISSUE THREAD

**Issue by musixite** [tailflow/laravel-orion#89]
when fetching data with a field that can return null, I can't filter the response with null objects. I have to use the 0 value.

api response
```
{"data":[
    {"id":1,"parent_id":null}
  ]
}
```

JS filtering (doesn't work)
```
query().where("parent_id", null)
```

JS filtering (works)
```
query().where("parent_id", 0)
```

**Comment by alexzarbn** [comment]
Hi @musixite,

Thank you for reporting the issue. I will look into it and get back to you soon.

**Comment by alexzarbn** [comment]
@musixite,

The problem is that you are not getting the correct results from the API when using TypeScript SDK or the results are correct, but the filtering on client side (using some other library) is not working as expected?
