### ISSUE TITLE
Global disallow auth

### ISSUE THREAD

**Issue by musixite** [tailflow/laravel-orion#90]
Right now we can only disallow auth for each model.

for testing purposes, it’s also be nice to disable it globally so that there would be no need to remove it for every model when auth is setup

**Comment by alexzarbn** [comment]
Hi @musixite,

Generally, it is preferable to setup auth from the very beginning to avoid problems in the future.
Introducing such option would encourage developers to avoid implementing the authorisation logic. For now, I do not think it is a desired behaviour.
