### ISSUE TITLE
best way to implement multi language ?

### ISSUE THREAD

**Issue by musixite** [tailflow/laravel-orion#91]
I'm wondering how I could setup the api to make it multi language ready (for the models)

Is it better to use a json field with the different languages
```
// Model Post
JSON field:  title: {'title_en': 'English title', 'title_fr': 'Titre france'}
```

or using a related Model for the translations
```
// Model Post (id)
// Model PostTranslations
fields: post_id,  title_en, title_fr
```
and then Fetch the api with an optional lang param in the query?

**Comment by alexzarbn** [comment]
Hi @musixite,

Generally, I would recommend using a json field for that.

Please use a specialized forums for questions of this nature in the future - GitHub issues are made specifically for things related to the repository itself, not general questions like this.
