### ISSUE TITLE
Nested Route `show` methods

### ISSUE THREAD

**Issue by DavidSprauel** [tailflow/laravel-orion#95]
Hey,

First thanks for this package, I find it amazing.
I've been using it to try it with one of my project and I have more a question than an issue.

I am using a nested relation as:
```php
Route::group(['prefix' => 'v1', 'middleware' => 'api'], function () {
    Orion::resource('users', UsersController::class)->withoutBatch();
    Orion::hasManyResource('users', 'programs', ProgramsController::class)->withoutBatch();
});
```

With that I have routes like `/api/v1/users/{user}/programs/{program}`
But when I request for example `/api/v1/users/1/programs/20`, the api returns me the program id 1 because the show methods uses the first key of the route which is the user id and not the program id.

Is that  the normal behaviour or am I missing something ?
Of course I could use the buildFetch method to customise the query but this is a simple fetch that endpoint so I assume it would works without any customisation.

Thanks ^^

**Comment by DavidSprauel** [comment]
Another example I have today:

`Orion::hasManyResource('programs', 'workouts', WorkoutsController::class)->withoutBatch();`

the `/api/v1/programs/{program}/workouts` return me all the workouts and not the one of the specified program.

**Comment by alexzarbn** [comment]
Hi @DavidSprauel,

Do `WorkoutsController` and `ProgramsController` classes extend `RelationController`?

**Comment by DavidSprauel** [comment]
@alexzarbn well then I missed something, thanks and sorry for the time ^^
