### ISSUE TITLE
Installation error: Installation request for doctrine/dbal (locked at 3.0.0) -> satisfiable by doctrine/dbal[3.0.0]

### ISSUE THREAD

**Issue by ykamal** [tailflow/laravel-orion#99]
Fresh Laravel 8 installation.

Full error description:
```
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Using version ^2.0 for tailflow/laravel-orion
./composer.json has been updated
Loading composer repositories with package information
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tailflow/laravel-orion ^2.0 -> satisfiable by tailflow/laravel-orion[2.0.0].
    - Can only install one of: doctrine/dbal[3.2.x-dev, 3.0.0].
    - Can only install one of: doctrine/dbal[3.2.x-dev, 3.0.0].
    - Can only install one of: doctrine/dbal[3.2.x-dev, 3.0.0].
    - Conclusion: install doctrine/dbal 3.2.x-dev
    - Installation request for doctrine/dbal (locked at 3.0.0) -> satisfiable by doctrine/dbal[3.0.0].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by ykamal** [comment]
I ran `composer require doctrine/dbal` and it installed the required dependencies. I just think this should be something handled by the documentation.

**Comment by alexzarbn** [comment]
Hi @ykamal,

What [method](https://laravel.com/docs/8.x#your-first-laravel-project) have you used to bootstrap the Laravel project? 

Creating a fresh Laravel project using Composer and then installing Laravel Orion works fine on my side 🤔

**Comment by ykamal** [comment]
> 
> 
> Hi @ykamal,
> 
> What [method](https://laravel.com/docs/8.x#your-first-laravel-project) have you used to bootstrap the Laravel project?
> 
> Creating a fresh Laravel project using Composer and then installing Laravel Orion works fine on my side 🤔

Hi. I am not using Docker. It's just a basic `laravel new orion-test` project. I did add some service providers to test differences. Here is the `AppServiceProvider.php` file:
```
/**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->register(RepositoryServiceProvider::class);
    }
```

**Comment by alexzarbn** [comment]
@ykamal Hmm, I am wondering, it that can be related to Composer 1. Could you please try to upgrade to Composer 2, and see if you still experience the same issue?

**Comment by ykamal** [comment]
@alexzarbn yep! That was it! After upgrading to Composer v2 and testing a fresh installation, there were no issues. I think we can close this one.

**Comment by alexzarbn** [comment]
@ykamal Okay, thank you for letting me know - I will add a note to the installation docs 👌🏻
